name: WakaTime Stats Update

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:    

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update WakaTime Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          commit_message: "chore: updated wakatime stats"
